apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirrorlit-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mirrorlit
    template:
        metadata:
            labels:
                app: mirrorlit
        spec:
            containers:
                - name: mirrorlit
                  image: ayj089/mirrorlit:latest
                  imagePullPolicy: Always
                  env:
                      - name: DB_HOST
                        value: "34.64.71.18"
                      - name: "DB_USER"
                        value: "myuser"
                      - name: "DB_PW"
                        value: "mypassword"
                      - name: "DB_PORT"
                        value: "3306"
                      - name: "DB_NAME"
                        value: "mirrorlit_db"
                  ports:
                      - containerPort: 3000
                        name: mirrorlit
