apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirrorlit-deploy
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mirrorlit
    template:
        metadata:
            labels:
                app: mirrorlit
        spec:
            containers:
                - name: mirrorlit
                  image: chsl123/mirrorlit:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                        name: mirrorlit
