apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirrorlit-deploy
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mirrorlit
    template:
        metadata:
            labels:
                app: mirrorlit
        spec:
            containers:
                - name: mirrorlit
                  image: chsl123/mirrorlit:latest
                  env:
                      - name: DB_HOST
                        value: "34.64.145.17"
                      - name: "DB_USER"
                        value: "cs"
                      - name: "DB_PW"
                        value: "mirrorlit"
                      - name: "DB_PORT"
                        value: "3306"
                      - name: "DB_NAME"
                        value: "mirrorlit_db"
                  ports:
                      - containerPort: 3000
                        name: mirrorlit
